new custom header in default metrics
cbb330/openhouse pull request #2
Opened 2024-07-28 01:52 UTC by cbb330

## Summary
new custom header "X-Client-Name" will propagate metrics to mdm. 

TODO: 
- [ ] parameterize the header to set of platforms to prevent malicious injection.
- [ ] refactor names and method of grabbing tags to not use collection and instead use Tags object (if needed / better)
- [ ] unittest

![image](https://github.com/user-attachments/assets/01cb8d3f-00c9-42e3-8a64-3382a46a2cc0)

## Changes

- [ ] Client-facing API Changes
- [ ] Internal API Changes
- [ ] Bug Fixes
- [ ] New Features
- [ ] Performance Improvements
- [ ] Code Style
- [ ] Refactoring
- [ ] Documentation
- [ ] Tests

For all the boxes checked, please include additional details of the changes made in this pull request.  

## Testing Done

- [ ] Manually Tested on local docker setup. Please include commands ran, and their output.
- [ ] Added new tests for the changes made.
- [ ] Updated existing tests to reflect the changes made.
- [ ] No tests added or updated. Please explain why. If unsure, please feel free to ask for help.
- [ ] Some other form of testing like staging or soak time in production. Please explain.

For all the boxes checked, include a detailed description of the testing done for the changes made in this pull request.

# Additional Information

- [ ] Breaking Changes
- [ ] Deprecations
- [ ] Large PR broken into smaller PRs, and PR plan linked in the description.

For all the boxes checked, include additional details of the changes made in this pull request.

2024-07-29 19:11 UTC, autumnust commented
What does X represent in the header key, or this is a convention?

2024-07-29 19:13 UTC, autumnust requested changes

2024-07-29 19:13 UTC, autumnust commented on services/tables/src/main/java/com/linkedin/openhouse/tables/config/MainApplicationConfig.java
> +  public static final List<String> ALLOWED_CLIENT_NAMES = Arrays.asList("trino", "spark");
what about catalog in a normal JVM, like workflow-scheduler's container? 
we've been shipping catalog in these environments and we can preset these values as part of shipped lib.

2024-07-29 19:13 UTC, autumnust commented on services/tables/src/main/java/com/linkedin/openhouse/tables/config/MainApplicationConfig.java
> +                ALLOWED_CLIENT_NAMES.contains(clientName) ? clientName : ""));
maybe something more informational instead of empty?

2024-07-29 19:13 UTC, autumnust commented on services/tables/src/main/java/com/linkedin/openhouse/tables/config/TablesMvcConfigurer.java
> +                  "/actuator/**", "/**/api-docs/**", "/**/swagger-ui/**", "/favicon.ico", "/error");
what is `favicon` ?

2024-07-30 01:45 UTC, merged

2024-07-30 02:24 UTC, cbb330 commented on client/secureclient/src/main/java/com/linkedin/openhouse/client/ssl/WebClientFactory.java
> +  @Setter private String sessionId = null;
this had a custom setter before, using lombok instead now to automate.

2024-07-30 02:25 UTC, cbb330 commented on client/secureclient/src/main/java/com/linkedin/openhouse/client/ssl/WebClientFactory.java
> +  private static final String HTTPHEADER_CLIENT_NAME = "X-Client-Name";
unfortunately can't use constant from services.common.Constants, so defining this string key twice in this PR.